spring:
  application:
    name: rag-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    dev:
      langchain4j: DEBUG

rag:
  ollama:
    base-url: ${OLLAMA_BASE_URL}
    model-name: ${OLLAMA_MODEL_NAME}
    chat-model: ${OLLAMA_CHAT_MODEL}
    timeout: 300s
  pgvector:
    dimension: 768
    table: vector_store
  ingestion:
    document-splitter:
      max-segment-size-in-chars: ${MAX_SEGMENT_SIZE_IN_CHARS:2000}
      max-overlap-size-in-chars: ${MAX_OVERLAP_SIZE_IN_CHARS:400}

server:
  port: ${SERVER_PORT:8081}
